version: '3.5'

services:
  pgdatabase:
    container_name: postgres_local
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=local_database
    volumes:
      - postgres_volume_local:/var/lib/postgresql/data:rw"
    ports:
      - "5442:5442"
    networks:
      - postgres-network

  pgadmin:
    container_name: pgadmin_local
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@local.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge
volumes:
  postgres_volume_local:
    external: true