server:
  port: 8184

spring:
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
        sql: DEBUG
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=customer&binaryTransfer=true&reWriteBatchedInserts=true
    username: postgres
    password: welcome
    driver-class-name: org.postgresql.Driver

  sql:
      init:
        platform: postgres
        mode: always
        schema: classpath:schema.sql
        data: classpath:data.sql

